"""Worker-side lineage helpers -- run inside the Glue/EMR worker,
NEVER on the Airflow scheduler.

Two responsibilities:

1. :func:`write_openlineage_yml` -- drop a config file next to
   ``dbt_project.yml`` so ``dbt-ol`` emits events to the requested
   store(s) via a ``composite`` transport (``file`` + optional custom
   SMUS transport).
2. :func:`upload_ol_events_to_s3` -- after dbt finishes, upload the
   NDJSON file to ``<s3_uri>/<parent_run>/<node_unique_id>.ndjson``.
   Portable format; any OpenLineage-aware tool can replay it later.

Kept in :mod:`dbt_aws.common.lineage.worker` (not
``.transport.smus``) so the worker's tiny import surface is obvious.
The actual custom SMUS transport class lives inline in the
``openlineage.yml`` that we WRITE -- OpenLineage discovers custom
transports via importable Python paths, so the class must land on
the worker's ``sys.path`` at run time. We do that by writing a
sibling ``_dbt_aws_ol_transport.py`` in the project dir.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)

# The name the composite transport looks up. Placed next to
# ``dbt_project.yml`` and imported via
# ``dbt_aws_ol_transport.SMUSTransport``. The path is injected into
# ``sys.path[0]`` inside the worker so this always resolves.
_TRANSPORT_MODULE_NAME = "dbt_aws_ol_transport"
_TRANSPORT_MODULE_FILE = f"{_TRANSPORT_MODULE_NAME}.py"

# Source of the custom transport class. Kept as a string literal (not
# a real .py in the wheel) because it's the smallest reliable way to
# put executable Python next to ``dbt_project.yml`` regardless of how
# the wheel is unpacked on the worker.
_SMUS_TRANSPORT_SRC = '''\
"""Custom OpenLineage transport: DataZone (SMUS) PostLineageEvent.

Auto-generated by dbt-aws. Do not edit -- overwritten on every worker
task startup.

Registered via ``openlineage.yml`` -> ``transport.type = "http"``-style
plugin resolution. OpenLineage's Python client looks up the FQCN
listed under ``type`` and instantiates it with the dict as ``config``.
"""

from __future__ import annotations

import json
import logging
import os

from openlineage.client.transport import Transport, Config  # type: ignore[import-untyped]

_log = logging.getLogger(__name__)


class SMUSTransportConfig(Config):
    """Minimal dataclass carrying the DataZone target."""

    def __init__(self, domain_id: str, region: str) -> None:
        self.domain_id = domain_id
        self.region = region

    @classmethod
    def from_dict(cls, params: dict) -> "SMUSTransportConfig":
        return cls(
            domain_id=params["domain_id"],
            region=params["region"],
        )


class SMUSTransport(Transport):
    """Emit each OpenLineage event to DataZone via
    ``datazone.post_lineage_event(domainIdentifier=..., event=<json bytes>)``.

    Never raises on failure -- lineage MUST NOT change the dbt exit
    code. All errors are logged.
    """

    kind = "smus"
    config_class = SMUSTransportConfig

    def __init__(self, config: SMUSTransportConfig) -> None:
        self.config = config
        # boto3 is lazy -- created on first emit so tests that never
        # emit can instantiate the transport without AWS creds.
        self._client = None

    def _boto(self):
        if self._client is None:
            import boto3
            self._client = boto3.client("datazone", region_name=self.config.region)
        return self._client

    def emit(self, event) -> None:
        try:
            # OpenLineage clients pass ``event`` as an already-JSON-serialisable
            # dict OR an object with ``.to_json()``. Handle both.
            if hasattr(event, "to_json"):
                payload = event.to_json()
            else:
                payload = json.dumps(event, default=str)
            self._boto().post_lineage_event(
                domainIdentifier=self.config.domain_id,
                event=payload.encode("utf-8"),
            )
        except Exception as exc:  # noqa: BLE001 -- lineage failure must not fail dbt
            _log.warning("SMUS lineage emit failed (event dropped): %s", exc)
'''


def write_openlineage_yml(
    *,
    project_dir: Path,
    namespace: str,
    ol_events_ndjson: Path,
    smus_domain_id: str | None,
    smus_region: str | None,
) -> Path:
    """Write an ``openlineage.yml`` next to ``dbt_project.yml`` that
    configures a ``composite`` transport wrapping:

    * ``file`` -> ``ol_events_ndjson`` (S3 archive store, later uploaded)
    * optional ``smus`` (:class:`SMUSTransport`) -> DataZone

    Returns the path to the written ``openlineage.yml``. Also writes
    the sibling ``_dbt_aws_ol_transport.py`` so OpenLineage can import
    the custom transport class by name.
    """
    project_dir.mkdir(parents=True, exist_ok=True)
    ol_events_ndjson.parent.mkdir(parents=True, exist_ok=True)

    transports: dict[str, dict[str, Any]] = {
        "file_archive": {
            "type": "file",
            "log_file_path": str(ol_events_ndjson),
            "append": True,
        }
    }
    if smus_domain_id:
        if not smus_region:
            raise ValueError("write_openlineage_yml: smus_domain_id set but smus_region is None")
        transports["smus"] = {
            # Fully-qualified path of the class we drop into the
            # project dir. ``sys.path[0]`` is set to that dir on the
            # worker, so ``dbt_aws_ol_transport.SMUSTransport``
            # resolves.
            "type": f"{_TRANSPORT_MODULE_NAME}.SMUSTransport",
            "domain_id": smus_domain_id,
            "region": smus_region,
        }

    config = {
        "transport": {
            "type": "composite",
            "transports": transports,
            "continue_on_failure": True,
        },
        # dbt-ol reads this as its default namespace.
        "namespace": namespace,
    }

    # OpenLineage happily reads either JSON or YAML from openlineage.yml.
    # JSON avoids a pyyaml dependency on the worker.
    ol_yml = project_dir / "openlineage.yml"
    ol_yml.write_text(json.dumps(config, indent=2), encoding="utf-8")
    _log.info("openlineage.yml written -> %s (stores=%s)", ol_yml, sorted(transports))

    (project_dir / _TRANSPORT_MODULE_FILE).write_text(_SMUS_TRANSPORT_SRC, encoding="utf-8")
    return ol_yml


def build_openlineage_env(
    *,
    parent_run_id: str,
    parent_job_name: str,
    parent_job_namespace: str,
    project_dir: Path,
    extra_env: dict[str, str] | None = None,
) -> dict[str, str]:
    """Return the env-vars ``dbt-ol`` reads to set the parent facet.

    Also sets ``OPENLINEAGE_CONFIG`` to the ``openlineage.yml`` sitting
    next to ``dbt_project.yml``, and prepends ``project_dir`` to
    ``PYTHONPATH`` so the custom SMUS transport class is importable.
    """
    ol_yml = project_dir / "openlineage.yml"
    existing_pypath = os.environ.get("PYTHONPATH", "")
    new_pypath = str(project_dir) + (os.pathsep + existing_pypath if existing_pypath else "")

    # dbt-ol / OpenLineage require runIds to be valid UUIDs (validated
    # against the OL spec regex). Airflow's ``run_id`` is a free-form
    # string like ``"manual__2026-07-03T07:00:00+00:00"`` or the
    # user-provided ``"ol-smoke-1783063773"``. We derive a stable UUID5
    # from the raw run_id so:
    #
    #   (a) the OL client accepts it;
    #   (b) two events from the same Airflow run get the SAME OL runId
    #       (deterministic hash);
    #   (c) SMUS / Marquez still see one parent per Airflow DAG execution.
    #
    # Namespace = a fixed UUID5(NAMESPACE_URL, "dbt-aws") so callers can
    # reproduce the mapping offline.
    import uuid as _uuid

    _NS = _uuid.uuid5(_uuid.NAMESPACE_URL, "dbt-aws")
    parent_run_uuid = str(_uuid.uuid5(_NS, parent_run_id))

    # dbt-ol expects the parent facet as a single composite env var
    # ``OPENLINEAGE_PARENT_ID = "<namespace>/<job_name>/<run_id>"``.
    # See ``openlineage.dbt.get_parent_run_metadata``.
    parent_id = f"{parent_job_namespace}/{parent_job_name}/{parent_run_uuid}"

    # dbt-ol internally calls ``subprocess.Popen(["dbt"] + args)``
    # (see ``openlineage.dbt.consume_local_artifacts``). On Glue the
    # dbt console script is installed to the user site ``bin/`` which
    # is NOT on PATH by default. Prepend it so ``dbt`` resolves.
    import site as _site

    _extra_bins = []
    try:
        user_base = _site.getuserbase()
        _extra_bins.append(f"{user_base}/bin")
    except Exception:  # noqa: BLE001 -- defensive
        pass
    _extra_bins.append("/home/hadoop/.local/bin")  # EMR / Glue default
    _extra_bins.append("/home/hadoop/env/bin")  # EMR Serverless venv-pack (spark.archives=venv#env)
    # ``./env/bin`` (relative to worker CWD) covers EMR Serverless
    # + venv-pack use cases where the venv is extracted under ``./env/``.
    _extra_bins.append("./env/bin")
    existing_path = os.environ.get("PATH", "")
    new_path = (
        os.pathsep.join([*_extra_bins, existing_path])
        if existing_path
        else os.pathsep.join(_extra_bins)
    )

    env: dict[str, str] = {
        "OPENLINEAGE_CONFIG": str(ol_yml),
        "OPENLINEAGE_NAMESPACE": parent_job_namespace,
        "OPENLINEAGE_PARENT_ID": parent_id,
        # Kept for backward-compat with other OL clients that read
        # the split env vars directly (spec-defined names).
        "OPENLINEAGE_PARENT_RUN_ID": parent_run_uuid,
        "OPENLINEAGE_PARENT_JOB_NAMESPACE": parent_job_namespace,
        "OPENLINEAGE_PARENT_JOB_NAME": parent_job_name,
        # Preserve the original Airflow run_id for humans reading
        # SMUS -- SMUS surfaces this in run metadata.
        "DBT_AWS_AIRFLOW_RUN_ID": parent_run_id,
        "PYTHONPATH": new_pypath,
        "PATH": new_path,
        # dbt-ol uses ``tqdm`` for its "Emitting OpenLineage events"
        # progress bar, which calls ``sys.stdout.fileno()``. On Glue
        # Interactive Sessions Livy replaces stdout with a StringIO-
        # like wrapper that raises ``UnsupportedOperation: fileno``.
        # ``TQDM_DISABLE=1`` silences the progress bar.
        "TQDM_DISABLE": "1",
    }
    if extra_env:
        env.update(extra_env)
    return env


def upload_ol_events_to_s3(
    *,
    ol_events_ndjson: Path,
    s3_uri: str,
    parent_run_id: str,
    node_unique_id: str,
) -> str | None:
    """Upload the local NDJSON events file to
    ``<s3_uri>/<parent_run_id>/<node_unique_id>.ndjson``.

    Returns the destination ``s3://`` URI on success, ``None`` when
    there was nothing to upload (dbt-ol never emitted -- e.g. dbt
    failed before running any node). Never raises: lineage upload
    must not change the dbt exit code.
    """
    if not ol_events_ndjson.is_file() or ol_events_ndjson.stat().st_size == 0:
        _log.info("ol upload: no events at %s -- nothing to upload", ol_events_ndjson)
        return None

    from urllib.parse import urlparse

    parsed = urlparse(s3_uri)
    if parsed.scheme != "s3" or not parsed.netloc:
        _log.warning("ol upload: bad s3_uri %r -- skipping", s3_uri)
        return None
    bucket = parsed.netloc
    prefix = parsed.path.lstrip("/").rstrip("/")
    # Sanitise for S3 keys: dbt unique_ids can contain '.' which S3 is
    # fine with, but keep it explicit for anyone reading the bucket.
    safe_node = node_unique_id.replace("/", "_")
    key = "/".join(p for p in (prefix, parent_run_id, f"{safe_node}.ndjson") if p)

    try:
        import boto3
        from botocore.exceptions import ClientError

        boto3.client("s3").upload_file(str(ol_events_ndjson), bucket, key)
    except (OSError, ClientError) as exc:  # narrow (); permission/auth errors surface
        _log.error("ol upload: failed to put s3://%s/%s: %s", bucket, key, exc)
        return None

    dest = f"s3://{bucket}/{key}"
    _log.info("ol upload: %s -> %s", ol_events_ndjson, dest)
    return dest
